#!/bin/bash

#echo "Enter your name"
#read name
#echo "My name is: ${name}"

#Different syntax
#read -p "Enter ur name" name1
#echo "Hello ${name1}"

#Arithematic operations
x=10
y=2
mul=$x*$y  #it will consider it as string
# using let
let mul1=$x*$y  # let tell var that its not a string
echo "$mul1"

#using $(())
echo "$(($x+$y))"   #$ tells echo that its not a string
